### ISSUE TITLE
[Meta] Change photo PNG to smaller JPG

### ISSUE THREAD

**Issue by bwbroersma** [minvws/nl-covid19-notification-lab-android#1]
Very nice you added an [impression picture](https://github.com/minvws/nl-covid19-notification-lab-android/blob/1d7bbb5fd0aca743b72b4e3f5a4f9d260fd45a6c/docs/impression.png) of the field test in [Assen](https://www.google.com/maps?hl=en&q=52.97518413,6.55412830) from this morning, but it's a photo in PNG format. PNG is not the best format for compressing photos, that's why it's 5.37 MB (that is served to everyone looking at the main repo). Probably change to a smaller JPG. Since GitHub is in a `container-lg` class which has a `max-width: 1012px` which effectively gives the full with of the Markdown `width: 914px`. Since lots of people have HDPI monitors, best practice is using ×2, giving a width of `1828px` to resize to. Since we use ×2, [we can go for a very low JPG quality of 40%](https://www.netvlies.nl/tips-updates/algemeen/design-interactie/retina-revolution/).
So probably you want to run something like:
```bash
curl https://raw.githubusercontent.com/minvws/nl-covid19-notification-lab-android/master/docs/impression.png\
 | convert - -auto-orient -colorspace sRGB -interlace JPEG -quality 40 -resize 1828x -sampling-factor 4:2:0 -strip impression.jpg
```

**Comment by dirkx** [comment]
Hey - we're trying to get things out & through the processes here as fast as we can. Priority is getting code ready, do field test & validate. The spit & finish of the processes around it are secondary. 

But as always in open source - scratch that itch & a PR to fix things would be most welcome!

**Comment by kkoenen** [comment]
Good catch, @bwbroersma ! :)
