### ISSUE TITLE
Potential Activity leak

### ISSUE THREAD

**Issue by jozuasijsling** [minvws/nl-covid19-notification-lab-android#3]
Seems that you're passing an Activity context to NotificationsRepository. You probably want to replace that with an Application context.

See code here:

https://github.com/minvws/nl-covid19-notification-lab-android/blob/1d7bbb5fd0aca743b72b4e3f5a4f9d260fd45a6c/app/src/main/java/nl/rijksoverheid/en/lab/MainActivity.kt#L53

Keep up the awesome work!

**Comment by hvisser** [comment]
Thanks! That seems to have slipped through! ~We're working on setting up ci for this, but~ if you want to PR a change for this, I'm happy to merge it.

**Comment by hvisser** [comment]
Fixed in https://github.com/minvws/nl-covid19-notification-lab-android/commit/72d52a3b20d449ce14e0c50db23af4a3f21f50f9#diff-fcb5dc10b11d7c6614537b260eada235
